import { Model, Schema, model, models } from "mongoose";
import { ObjectId } from "mongoose";

interface AutoGeneratedPlaylistDocument {
  title: string;
  items: ObjectId[];
}

const autoGeneratedPlaylistSchema = new Schema<AutoGeneratedPlaylistDocument>(
  {
    title: {
      type: String,
      required: true,
    },
    items: [
      {
        type: Schema.Types.ObjectId,
        required: true,
        ref: "Audio",
      },
    ],
  },
  { timestamps: true }
);

const AutoGeneratedPlaylists =
  models.AutoGeneratedPlaylists ||
  model("AutoGeneratedPlaylists", autoGeneratedPlaylistSchema);

export default AutoGeneratedPlaylists as Model<AutoGeneratedPlaylistDocument>;
